# Generated by Django 5.1.7 on 2025-05-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personality_mode', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('research_assistant', 'Research Assistant'), ('comedian', 'Comedian')], default='casual', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='agentic.sessionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('proactive_message', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField()),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('search_result_urls', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='agentic.sessionrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
